version: '3.8'

services:
  soundcloud-fetcher:
    image: tsshadow/music-management-tools:latest
    container_name: muma-soundcloud-fetcher
    depends_on:
      - db
    command: ["python", "tools/soundcloud_fetcher.py"]
    environment:
      - PYTHONPATH=/app:/app/services/downloader
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=music-management
      - DB_PASS=Properly-Urologist9-Onlooker-Stupor-Triage-Rocket
      - DB_DB=music-management
      - music_folder_path=/mnt/music
    volumes:
      - /docker/music-management/importer:/app/data
      - /mnt/music:/mnt/music
      - /docker/music-management/shared:/shared
    networks:
      - music-management_db

networks:
  music-management_db:
    external: true
