version: "3.9"

services:
  db:
    image: mariadb:10.6
    container_name: music-management-db-1
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_DB}
    ports:
      - "3306:3306"
    volumes:
      - ${HOST_DATA_PATH}/mariadb:/var/lib/mysql
    networks:
      - music-management_db

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: music-management-phpmyadmin-1
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8002:80"
    networks:
      - music-management_db

  control-center:
    image: ${DOCKER_USER}/${IMAGE_MANAGEMENT}:latest
    container_name: muma-control-center
    restart: unless-stopped
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_DB=${DB_DB}
      - PHPMYADMIN_URL=${PHPMYADMIN_URL}
    ports:
      - "8003:8000"
    networks:
      - music-management_db

  # importer_api:
  #   image: ${DOCKER_USER}/${IMAGE_APP}:latest
  #   container_name: muma-importer-api
  #   restart: unless-stopped
  #   depends_on:
  #     - db
  #   command:
  #     [
  #       "uvicorn",
  #       "services.common.api.server:app",
  #       "--host",
  #       "0.0.0.0",
  #       "--port",
  #       "8001"
  #     ]
  #   environment:
  #     PORT: 8001
  #     PYTHONPATH: /app:/app/services/downloader
  #     DB_HOST: ${DB_HOST}
  #     DB_PORT: ${DB_PORT}
  #     DB_USER: ${DB_USER}
  #     DB_PASS: ${DB_PASS}
  #     DB_DB: ${DB_DB}
  #     telegram_api_id: "${telegram_api_id}"
  #     telegram_api_hash: "${telegram_api_hash}"
  #     telegram_session: ${telegram_session}
  #     API_KEY: ""
  #     CORS_ORIGINS: "*"
  #   ports:
  #     - "7001:8001"
  #   volumes:
  #     - ${HOST_DATA_PATH}/importer:/app/data
  #     - ${HOST_MUSIC_PATH}:/mnt/music
  #     - ${HOST_DATA_PATH}/shared:/shared
  #   networks:
  #     - music-management_db

  importer_worker:
    image: ${DOCKER_USER}/${IMAGE_APP}:latest
    container_name: muma-importer-worker
    restart: unless-stopped
    depends_on:
      - db
    command:
      [
        "python",
        "services/importer/importer_service.py",
        "--repeat",
        "--sleeptime",
        "300"
      ]
    environment:
      PYTHONPATH: /app:/app/services/downloader
      debug: "${debug}"
      dryrun: "False"
      rescan: "True"
      delimiter: "${delimiter}"
      import_folder_path: ${import_folder_path}
      eps_folder_path: ${eps_folder_path}
      music_folder_path: ${music_folder_path}
      youtube_folder: ${youtube_folder}
      youtube_archive: ${youtube_archive}
      youtube_accounts: ${youtube_accounts}
      soundcloud_folder: ${soundcloud_folder}
      soundcloud_archive: ${soundcloud_archive}
      soundcloud_accounts: ${soundcloud_accounts}
      ffmpeg_location: /usr/local/bin
      ffmpeg-location: /usr/local/bin
      telegram_folder: ${telegram_folder}
      ytdlp: yt-dlp
      telegram_api_id: "${telegram_api_id}"
      telegram_api_hash: "${telegram_api_hash}"
      telegram_session: ${telegram_session}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_DB: ${DB_DB}
      ask-for-missing: "false"
    volumes:
      - ${HOST_DATA_PATH}/importer:/app/data
      - ${HOST_MUSIC_PATH}:/mnt/music
      - ${HOST_DATA_PATH}/shared:/shared
    networks:
      - music-management_db

  youtube_worker:
    image: ${DOCKER_USER}/${IMAGE_APP}:latest
    container_name: muma-youtube-worker
    restart: unless-stopped
    depends_on:
      - db
    command:
      [
        "python",
        "services/downloader/downloader_service.py",
        "--step",
        "youtube",
        "--repeat",
        "--sleeptime",
        "300",
        "--break-on-existing"
      ]
    environment:
      PYTHONPATH: /app:/app/services/downloader
      debug: "${debug}"
      dryrun: "False"
      rescan: "True"
      delimiter: "${delimiter}"
      import_folder_path: ${import_folder_path}
      eps_folder_path: ${eps_folder_path}
      music_folder_path: ${music_folder_path}
      youtube_folder: ${youtube_folder}
      youtube_archive: ${youtube_archive}
      youtube_accounts: ${youtube_accounts}
      soundcloud_folder: ${soundcloud_folder}
      soundcloud_archive: ${soundcloud_archive}
      soundcloud_accounts: ${soundcloud_accounts}
      ffmpeg_location: /usr/local/bin
      ffmpeg-location: /usr/local/bin
      telegram_folder: ${telegram_folder}
      ytdlp: yt-dlp
      telegram_api_id: "${telegram_api_id}"
      telegram_api_hash: "${telegram_api_hash}"
      telegram_session: ${telegram_session}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_DB: ${DB_DB}
      ask-for-missing: "false"
    volumes:
      - ${HOST_DATA_PATH}/importer:/app/data
      - ${HOST_MUSIC_PATH}:/mnt/music
      - ${HOST_DATA_PATH}/shared:/shared
    networks:
      - music-management_db

  soundcloud_worker:
    image: ${DOCKER_USER}/${IMAGE_APP}:latest
    container_name: muma-soundcloud-worker
    restart: unless-stopped
    depends_on:
      - db
    command:
      [
        "python",
        "services/downloader/downloader_service.py",
        "--step",
        "soundcloud",
        "--repeat",
        "--sleeptime",
        "300",
        "--break-on-existing"
      ]
    environment:
      PYTHONPATH: /app:/app/services/downloader
      debug: "${debug}"
      dryrun: "False"
      rescan: "True"
      delimiter: "${delimiter}"
      import_folder_path: ${import_folder_path}
      eps_folder_path: ${eps_folder_path}
      music_folder_path: ${music_folder_path}
      youtube_folder: ${youtube_folder}
      youtube_archive: ${youtube_archive}
      youtube_accounts: ${youtube_accounts}
      soundcloud_folder: ${soundcloud_folder}
      soundcloud_archive: ${soundcloud_archive}
      soundcloud_accounts: ${soundcloud_accounts}
      ffmpeg_location: /usr/local/bin
      ffmpeg-location: /usr/local/bin
      telegram_folder: ${telegram_folder}
      ytdlp: yt-dlp
      telegram_api_id: "${telegram_api_id}"
      telegram_api_hash: "${telegram_api_hash}"
      telegram_session: ${telegram_session}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_DB: ${DB_DB}
      ask-for-missing: "false"
    volumes:
      - ${HOST_DATA_PATH}/importer:/app/data
      - ${HOST_MUSIC_PATH}:/mnt/music
      - ${HOST_DATA_PATH}/shared:/shared
    networks:
      - music-management_db

  soundcloud_worker_full_once:
    image: ${DOCKER_USER}/${IMAGE_APP}:latest
    container_name: muma-soundcloud-worker-full-once
    restart: unless-stopped
    depends_on:
      - db
    command:
      [
        "python",
        "services/downloader/downloader_service.py",
        "--step",
        "soundcloud",
        "--no-break-on-existing"
      ]
    environment:
      PYTHONPATH: /app:/app/services/downloader
      debug: "${debug}"
      dryrun: "False"
      rescan: "True"
      delimiter: "${delimiter}"
      import_folder_path: ${import_folder_path}
      eps_folder_path: ${eps_folder_path}
      music_folder_path: ${music_folder_path}
      youtube_folder: ${youtube_folder}
      youtube_archive: ${youtube_archive}
      youtube_accounts: ${youtube_accounts}
      soundcloud_folder: ${soundcloud_folder}
      soundcloud_archive: ${soundcloud_archive}
      soundcloud_accounts: ${soundcloud_accounts}
      ffmpeg_location: /usr/local/bin
      ffmpeg-location: /usr/local/bin
      telegram_folder: ${telegram_folder}
      ytdlp: yt-dlp
      telegram_api_id: "${telegram_api_id}"
      telegram_api_hash: "${telegram_api_hash}"
      telegram_session: ${telegram_session}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_DB: ${DB_DB}
      ask-for-missing: "false"
    volumes:
      - ${HOST_DATA_PATH}/importer:/app/data
      - ${HOST_MUSIC_PATH}:/mnt/music
      - ${HOST_DATA_PATH}/shared:/shared
    networks:
      - music-management_db

  telegram_worker:
    image: ${DOCKER_USER}/${IMAGE_APP}:latest
    container_name: muma-telegram-worker
    restart: unless-stopped
    depends_on:
      - db
    command:
      [
        "python",
        "services/downloader/downloader_service.py",
        "--step",
        "telegram",
        "--repeat",
        "--sleeptime",
        "300"
      ]
    environment:
      PYTHONPATH: /app:/app/services/downloader
      debug: "${debug}"
      dryrun: "False"
      delimiter: "${delimiter}"
      music_folder_path: ${music_folder_path}
      telegram_folder: ${telegram_folder}
      telegram_api_id: "${telegram_api_id}"
      telegram_api_hash: "${telegram_api_hash}"
      telegram_session: ${telegram_session}
      telegram_accounts: "${telegram_accounts}" 
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_DB: ${DB_DB}
    volumes:
      - ${HOST_DATA_PATH}/importer:/app/data
      - ${HOST_MUSIC_PATH}:/mnt/music
      - ${HOST_DATA_PATH}/shared:/shared
    networks:
      - music-management_db  
    stdin_open: true
    tty: true

  tagger_worker:
    image: ${DOCKER_USER}/${IMAGE_APP}:latest
    container_name: muma-tagger-worker
    restart: unless-stopped
    depends_on:
      - db
    command:
      [
        "python",
        "services/tagger/tagger_service.py",
        "--repeat",
        "--sleeptime",
        "300"
      ]
    environment:
      PYTHONPATH: /app:/app/services/downloader
      debug: "${debug}"
      delimiter: "${delimiter}"
      import_folder_path: ${import_folder_path}
      eps_folder_path: ${eps_folder_path}
      music_folder_path: ${music_folder_path}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_DB: ${DB_DB}
    volumes:
      - ${HOST_DATA_PATH}/importer:/app/data
      - ${HOST_MUSIC_PATH}:/mnt/music
      - ${HOST_DATA_PATH}/shared:/shared
    networks:
      - music-management_db

  soundcloud-fetcher:
    image: ${DOCKER_USER}/${IMAGE_TOOLS}:latest
    container_name: muma-soundcloud-fetcher
    depends_on:
      - db
    command: ["python", "tools/soundcloud_fetcher.py"]
    environment:
      - PYTHONPATH=/app:/app/services/downloader
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_DB=${DB_DB}
      - music_folder_path=${music_folder_path}
    volumes:
      - ${HOST_DATA_PATH}/importer:/app/data
      - ${HOST_MUSIC_PATH}:/mnt/music
      - ${HOST_DATA_PATH}/shared:/shared
    networks:
      - music-management_db

  genre-processor:
    image: ${DOCKER_USER}/${IMAGE_TOOLS}:latest
    container_name: genre-processor
    depends_on:
      - db
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_DB=${DB_DB}
    stdin_open: true
    tty: true
    networks:
      - music-management_db

  ml-analyzer:
    image: ${DOCKER_USER}/${IMAGE_ML}:latest
    container_name: muma-ml-analyzer
    depends_on:
      - db
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_DB=${DB_DB}
      - PYTHONPATH=/app
    volumes:
      - ${HOST_MUSIC_PATH}:/mnt/music
      - ${HOST_DATA_PATH}/shared:/shared
    networks:
      - music-management_db

  firefox:
    image: jlesage/firefox:latest
    container_name: muma-firefox
    restart: unless-stopped
    shm_size: "1gb"
    environment:
      TZ: Europe/Amsterdam
      WEB_AUTHENTICATION: "1"
      SECURE_CONNECTION: "0"
      DISABLE_GPU: "1"
    ports:
      - "7003:5800"
    volumes:
      - ${HOST_DATA_PATH}/firefox:/config
      - ${HOST_DATA_PATH}/shared:/shared
    networks:
      - music-management_db

networks:
  music-management_db:
    name: music-management_db
    driver: bridge
