ARG DOCKER_USER
ARG VERSION=latest

FROM ${DOCKER_USER}/muma-base:${VERSION}
WORKDIR /app

COPY services/rating-system/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy backend code
COPY services/rating-system/ /app/services/rating-system/

ENV PYTHONPATH=/app
EXPOSE 8000

CMD ["uvicorn", "services.rating-system.main:app", "--host", "0.0.0.0", "--port", "8000"]
