ARG DOCKER_USER
ARG VERSION=latest

FROM ${DOCKER_USER}/muma-base:${VERSION}
WORKDIR /app

COPY services/scrobble-service/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy backend code
COPY services/scrobble-service/ /app/services/scrobble-service/

ENV PYTHONPATH=/app
EXPOSE 8000

CMD ["uvicorn", "services.scrobble-service.main:app", "--host", "0.0.0.0", "--port", "8000"]
