# syntax=docker/dockerfile:1
ARG DOCKER_USER
ARG VERSION=latest
FROM ${DOCKER_USER}/muma-base:${VERSION}

WORKDIR /app

# Rating System specific code
COPY services/rating-system/ /app/services/rating-system/

CMD ["uvicorn", "services.rating-system.main:app", "--host", "0.0.0.0", "--port", "8000"]
