# syntax=docker/dockerfile:1
ARG DOCKER_USER
ARG VERSION=latest
FROM ${DOCKER_USER}/muma-base:${VERSION}

WORKDIR /app

# Tagger specific dependencies
RUN pip install --no-cache-dir mutagen librosa numpy

# Tagger specific code
COPY services/tagger/ /app/services/tagger/
COPY services/tagger/RELEASE_NOTES.md /app/services/tagger/

CMD ["python", "services/tagger/tagger_service.py", "--repeat"]
